version: '3.9'
services:
  web-app:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./ac_app:/ac_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ac_db
      DB_USER: admin
      DB_PASS: admin
      
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ac_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ac_data:/var/lib/postgresql/data/
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  ac_data: null