# Generated by Django 4.2.7 on 2024-05-27 11:42

from django.db import migrations, models
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=space.models.Constellation.upload_img)),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('quadrant', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
