# Generated by Django 4.2.7 on 2024-05-29 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0004_spectralclass_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_spectrum', models.CharField(blank=True, max_length=50)),
                ('galaxy', models.CharField(blank=True, max_length=100)),
                ('apparent_magnitude', models.CharField(blank=True, max_length=50)),
                ('absolute_magnitude', models.CharField(blank=True, max_length=50)),
                ('distance', models.CharField(blank=True, max_length=100)),
                ('radial_velocity', models.CharField(blank=True, max_length=50)),
                ('mass', models.FloatField(blank=True, null=True, verbose_name='Mass (in solar masses)')),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age_unit', models.IntegerField(blank=True, choices=[(1, 'Million Years'), (2, 'Billion Years')], default=1, verbose_name='Unit of Age')),
                ('star', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.star')),
            ],
            options={
                'verbose_name': 'Characteristics',
                'verbose_name_plural': 'Key characteristics',
            },
        ),
        migrations.CreateModel(
            name='FavoriteStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='space.star')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'star')},
            },
        ),
    ]
